version: '3'

services:

  postgres:
    ports:
      - '5432:5432'
    restart: always 
    image: postgres:12-alpine
    environment:
    - POSTGRES_USER=pguser
    - POSTGRES_PASSWORD=password
    volumes:
      - ./pginit:/docker-entrypoint-initdb.d

    

  
  
  